language: java    
jdk: openjdk8
cache:
  directories:
   - $HOME/.m2
   - $HOME/.sonar/cache
install:
  - mvn package -B
script:
  - xvfb-run mvn verify -B
  - mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN
before_cache:
  - rm -fr $HOME/.m2/repository/nl/esciencecenter/e3dchem
